// MIT License Copyright (c) Florian Grimm

namespace Brimborium.Extensions.Logging.TestList;

/// <summary>
/// Contains a list of <see cref="TestLoggerItem"/>.
/// A snapshot generated by <see cref="TestLoggerBuffer.GetSnapshot"/>.
/// Used for TUnit Assert.That(snapshot)...
/// </summary>
/// <example>
/// <code>
/// var testLoggerBuffer = appServiceProvider.GetTestLoggerBuffer();
/// var snapshot = testLoggerBuffer.GetSnapshot();
/// _ = await Assert.That(snapshot).FindNextLoggerMessage(() => LoggerExtension.LogTestA);
/// </code>
/// </example>
public sealed class TestLoggerSnapshot {
    private readonly TestLoggerItem[] _ListItem;

    public TestLoggerSnapshot(TestLoggerItem[] listItem) {
        this._ListItem = listItem;
        this.PreviousIndex = -1;
        this.Index = -1;
    }

    public TestLoggerSnapshot Clone()
        => new TestLoggerSnapshot(this._ListItem) { 
            Index = this.Index,
            PreviousIndex = this.PreviousIndex,
        };

    /// <summary>
    /// The current found index (starting by -1).
    /// </summary>
    public int Index { get; set; }

    /// <summary>
    /// Get the currently found item
    /// </summary>
    /// <returns>The item or default.</returns>
    public TestLoggerItem? GetCurrentItem() {
        var index = this.Index;
        if (0 <= index && index < this._ListItem.Length) {
            return this._ListItem[index];
        } else {
            return default;
        }
    }

    /// <summary>
    /// Get the <paramref name="index"/> item
    /// </summary>
    /// <param name="index">the index</param>
    /// <returns>the item or default if out of range.</returns>
    public TestLoggerItem? GetItemByIndex(int index) {
        if (0 <= index && index < this._ListItem.Length) {
            return this._ListItem[index];
        } else {
            return default;
        }
    }

    /// <summary>
    /// The previous (found) index
    /// </summary>
    public int PreviousIndex { get; set; }

    /// <summary>
    /// Get the <see cref="TestLoggerSnapshot.PreviousIndex"/> item.
    /// </summary>
    /// <returns>the item or default</returns>
    public TestLoggerItem? GetPreviousItem() {
        var index = this.PreviousIndex;
        if (0 <= index && index < this._ListItem.Length) {
            return this._ListItem[index];
        } else {
            return default;
        }
    }

    /// <summary>
    /// Starting from this.Index+1 if found Index, PreviousIndex will be changed
    /// </summary>
    /// <param name="searchFor">Search for this.</param>
    /// <param name="found">returns the first matched item.</param>
    /// <returns>true if matched item found.</returns>
    public bool TryFindNext(TestLoggerItem searchFor, [MaybeNullWhen(false)] out TestLoggerItem found) {
        var index = this.Index + 1;
        {
            while (index < this._ListItem.Length) {
                var item = this._ListItem[index];
                if (item.IsEqualTo(searchFor) is null) {
                    found = item;
                    this.PreviousIndex = this.Index;
                    this.Index = index;
                    return true;
                }
                index++;
            }
        }
        {
            found = default;
            return false;
        }
    }

    /// <summary>
    /// Seek <paramref name="nextIndex"/> to Index.
    /// </summary>
    /// <param name="nextIndex">jump items forward/back.</param>
    /// <returns>true if possible</returns>
    public bool SeekAbsolute(int nextIndex) {
        if (0 <= nextIndex && nextIndex < this._ListItem.Length) {
            this.PreviousIndex = this.Index;
            this.Index = nextIndex;
            return true;
        } else {
            return false;
        }
    }

    /// <summary>
    /// Seek <paramref name="difference"/> form the current Index.
    /// </summary>
    /// <param name="difference">jump items forward/back.</param>
    /// <returns>true if possible</returns>
    public bool SeekRelative(int difference) {
        var nextIndex = this.Index + difference;
        if (0 <= nextIndex && nextIndex < this._ListItem.Length) {
            this.PreviousIndex = this.Index;
            this.Index = nextIndex;
            return true;
        } else {
            return false;
        }
    }
}